development: &common_settings
  api_key: "AIzaSyApfbQ8ByIK99wF7SKDtsiz9mmKp7TNFqQ"
  country: "us"
  per_page: 20
  cache_ttl: 60
  query: "Ruby on Rails"
production:
  <<: *common_settings
test:
  <<: *common_settings