require 'googlebooks'
require "will_paginate-bootstrap"
require 'will_paginate/array'
require 'sass'
require 'memcachier'
require 'dalli'
require "./models/book"
#require "pry"
#require "pry-debugger"